FROM golang:1.14.6

WORKDIR /project

COPY ./go.* ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go install -v ./cmd/server/visualizer


FROM debian:buster-slim

RUN apt-get update -y
RUN apt-get install -y chromium
RUN apt-get install -y chromium-driver

COPY --from=0 /go/bin/visualizer /bin/visualizer

USER 1001

CMD ["/bin/visualizer"]
