name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        run: go get -v -t -d ./...

      - name: build
        run: make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30

      - name: test
        run: make test.s
