name: ci

on:
  push:
    tags:
      - v*
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: dependencies
        run: go mod download

      - name: build.c
        run: make build.c

      - name: build.v
        run: make build.v

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.3

      - name: test
        run: make test.s
